wip
younginnovations/iatipublisher pull request #1133
Opened 2023-03-15 03:56 UTC by rajkarnikar11

2023-04-13 03:43 UTC, man-git007 commented
@rajkarnikar11 What is the status of this PR?

cc @SauravSilwal10

2023-04-17 03:59 UTC, sriza requested changes

2023-04-17 03:59 UTC, sriza commented on resources/assets/js/app.ts
> +    if (supportButton !== null) {
new line

2023-04-17 03:59 UTC, sriza commented on resources/assets/js/views/activity/bulk-publish/BulkPublishing.vue
> +  console.log('mounted');
remove console log

2023-04-17 03:59 UTC, sriza commented on resources/assets/js/components/sections/ProgressLoader.vue
> +  if (supportButton !== null) {
add a new line

2023-04-17 03:59 UTC, sriza commented on resources/assets/js/components/sections/ProgressLoader.vue
> +  if (supportButton !== null) {
add a new line

2023-04-17 04:50 UTC, sriza approved these changes

2023-04-17 04:57 UTC, merged