Draft: 1171-xls-download
younginnovations/iatipublisher pull request #1173
Opened 2023-04-13 11:35 UTC by A4family

2023-06-08 10:43 UTC, Sanilblank requested changes

2023-06-08 10:43 UTC, Sanilblank commented on .husky/pre-commit
> +# php artisan test && \
remove comment

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/IndicatorExport.php
> +            foreach (Arr::collapse($mapped[$sheetName]['Indicator Identifier']) as $value) {
new line

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/OptionExport.php
> +        return view('Export.optionExport', ['data' => $data]);
use readJsonFile('Exports/XlsExportTemplate/' . $this->fileName . '.json') directly instead of declaring and using $data

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
function definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +     * @return array|mixed
is return type mixed? or just array , change this

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +     * @return array|mixed
change to either just array or mixed

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    protected function getMappedPeriodData($indicatorIds, $indicatorMapper, $appendIdentifier, $finalIdentifierKey, $mapped, $sheetName, $downloadXlsService): mixed
try to not use mixed return type

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +            foreach (Arr::collapse($mapped[$sheetName]['Period Identifier']) as $value) {
new line

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +            foreach (Arr::collapse($mapped[$sheetName]['Period Identifier']) as $value) {
new line

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/Exports/PeriodExport.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Models/Download/DownloadStatus.php
> +    protected $casts = [
doc comment

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Models/User/User.php
> +    /**
definition

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Repositories/Activity/ResultRepository.php
> +     * @return mixed
dont use mixed

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Services/Download/DownloadXlsService.php
> +     * @return mixed
dont use mixed

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Services/Download/DownloadXlsService.php
> +     * @return mixed
no mixewd

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Services/Download/DownloadXlsService.php
> +     * @return \Illuminate\Database\Eloquent\Builder|Model|mixed|object|null
Import this and remove mixed. Also, add return type to function.

2023-06-08 10:43 UTC, Sanilblank commented on app/IATI/Traits/XlsDownloadTrait.php
> +     * @return mixed
remove mixed if possible

2023-06-08 10:43 UTC, Sanilblank commented on app/Jobs/ExportXlsJob.php
> +     *
missing params

2023-06-08 10:43 UTC, Sanilblank commented on app/Jobs/XlsExportMailJob.php
> +     *
params

2023-06-08 10:43 UTC, Sanilblank commented on app/Jobs/XlsExportMailJob.php
> +        if (empty($awsCancelStatusFile)) {
use direclty

2023-06-08 10:43 UTC, Sanilblank commented on app/XlsImporter/Foundation/Mapper/Traits/XlsMapperHelper.php
>       * @return mixed
change mixed

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/components/BulkpublishWithXls.vue
> +//inject
remove

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/components/BulkpublishWithXls.vue
> +// let activities = ref(paStorage.value.publishingActivities.activities);
remove

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/components/BulkpublishWithXls.vue
> +        if (completed.value === 'completed') {
newline

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/components/BulkpublishWithXls.vue
> +// const retryPublishing = () => {
remove commented code

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/views/activity/ActivityIndex.vue
> +        // if (res?.data?.status?.status === 'completed') {
remove

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/views/activity/ActivityIndex.vue
> +          if (
newline

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/views/activity/ActivityIndex.vue
>        if (props.toast.message !== '') {
new line

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/views/activity/bulk-publish/BulkPublishing.vue
> +        <!-- <div v-else class="minus cursor-pointer" @click="toggleWindow"></div> -->
remove

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/views/activity/bulk-publish/PublishSelected.vue
> +    <!-- <BulkPublishing
remove

2023-06-08 10:43 UTC, Sanilblank commented on resources/assets/js/views/activity/partials/DownloadActivityButton.vue
> +      if (queryParameters.length === 2) {
new line

2023-06-08 10:43 UTC, Sanilblank commented on resources/views/Export/xlsExport.blade.php
> +{{--        <th><b>{{ $primaryIdentifier  }}</b></th>--}}
remove

2023-06-08 10:43 UTC, Sanilblank commented on routes/download.php
> +    // Route::get('activities/download-codes/{download?}', [DownloadCodesController::class, , 'downloadCodes'])->name('activities.download-codes');
remove

2023-06-08 11:33 UTC, A4family commented on app/IATI/Repositories/Activity/IndicatorRepository.php
> +     * @return mixed
It is returning query

2023-06-09 02:23 UTC, sriza requested changes

2023-06-09 02:23 UTC, sriza commented on app/Helpers/general.php
> +if (!function_exists('generateRandomCharacters')) {
add helper function to utils.php

2023-06-09 02:23 UTC, sriza commented on app/Helpers/general.php
> +    function generateRandomCharacters($length): string
add helper function to utils.php

2023-06-09 02:23 UTC, sriza commented on app/Http/Controllers/Admin/Download/DownloadActivityController.php
> +        AuditService $auditService,
incomplete php docs.. add all params

2023-06-09 02:23 UTC, sriza commented on app/IATI/Repositories/Activity/ActivityRepository.php
> +    public function getAllActivitiesQueryToDownload($organizationId, $queryParams): object
Check if we already have similar method, if we do reuse it

2023-06-09 02:23 UTC, sriza commented on app/IATI/Traits/XlsDownloadTrait.php
> +            foreach ($datum as &$array) {
a new line

2023-06-09 02:23 UTC, sriza commented on app/IATI/Traits/XlsDownloadTrait.php
> +            $keyData = $datum;
add a new line

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/ActivityDownload.vue
> +  let apiUrl = `${(downloadApiUrl as Ref).value.split()[0].split('/')[3]}/${
const as it is unchanged

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/ActivityDownload.vue
> +    let fileName = res.headers['content-disposition'].split('filename=')[1];
const for both variables

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/ActivityDownload.vue
> +  let apiUrl = 'activities/retry-xls-download';
const

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/ActivityDownload.vue
> +
remove new line

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/BulkpublishWithXls.vue
> +          console.log('clear interval');
remove console

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/BulkpublishWithXls.vue
> +  axios.get(endpoint).then((res) => {
add a new line above

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/components/BulkpublishWithXls.vue
> +onMounted(() => {
place the onmounted after props

2023-06-09 02:23 UTC, sriza commented on resources/assets/js/views/activity/ActivityIndex.vue
> +      const checkDownload = setInterval(function () {
add a new line above

2023-06-09 02:23 UTC, sriza commented on resources/views/Export/xlsExport.blade.php
> +                    <td> @if($loop->first) {{ trim($identifier)  }} @endif</td>
seperate in multiple lines

2023-06-13 11:54 UTC, sriza requested changes

2023-06-13 12:09 UTC, sriza commented on resources/assets/js/components/XlsUploadIndicator.vue
> +console.log(publishingActivities.value);
remove

2023-06-13 12:09 UTC, sriza commented on resources/assets/js/components/XlsUploadIndicator.vue
> +        console.log('translate');
remove

2023-06-13 12:09 UTC, sriza commented on resources/assets/js/views/activity/ActivityIndex.vue
> +          console.log('completed');
remove

2023-06-13 12:23 UTC, sriza approved these changes

2023-06-13 12:31 UTC, Sanilblank approved these changes

2023-06-14 03:54 UTC, merged