Draft: 1192-migrating-organizations-who-have-already-registered-on-iati-publ…
younginnovations/iatipublisher pull request #1195
Opened 2023-04-27 07:22 UTC by Sanilblank

…isher

* [x] Created command that will be used to migrate the existing organization

2023-05-02 06:03 UTC, sriza requested changes

2023-05-03 05:23 UTC, sriza approved these changes

2023-05-03 05:23 UTC, sriza commented on app/Console/Commands/MigrateExistingOrganizationCommand.php
> +
add strict type

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/LogFunctionTrait.php
> +    private function logActivityNotPublishedBecauseOfTokenVerification($aidStreamOrganization, $iatiOrganization, $activityPublished)
Return type not defined

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/LogFunctionTrait.php
> +    private function logActivityNotPublishedBecauseOfPublisherVerification($aidStreamOrganization, $iatiOrganization, $activityPublished)
Return type not defined

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/LogFunctionTrait.php
> +    private function logActivityNotPublishedBecauseOrganizationSettingNotValid($aidStreamOrganization, $iatiOrganization, $activityPublished)
return type not defined

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/LogFunctionTrait.php
> +    private function logOrganizationNotPublishedBecauseTokenVerification($aidStreamOrganization, $iatiOrganization, $organizationPublished): mixed
return type should be void.

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/LogFunctionTrait.php
> +    private function logOrganizationNotPublishedBecausePublisherVerification($aidStreamOrganization, $iatiOrganization, $organizationPublished): mixed
return type should be void.

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/LogFunctionTrait.php
> +    private function logOrganizationNotPublishedBecauseOrganizationSettingIsNotValid($aidStreamOrganization, $iatiOrganization, $organizationPublished, $setting)
return type not defined

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/MigrateActivityTrait.php
> +     * @return void
add new line for different phpdocs type

2023-05-03 05:25 UTC, A4family commented on app/IATI/Traits/MigrateDocumentFileTrait.php
> +     * @return void
add a new line between @return and @throws

2023-05-03 05:35 UTC, merged