draft: 1209-freeze-input-fields-based-on-conditions
younginnovations/iatipublisher pull request #1210
Opened 2023-05-18 05:12 UTC by A4family

… activity level or in transaction level according to conditions

2023-06-06 07:28 UTC, sriza commented on app/Http/Controllers/Admin/Activity/ActivityController.php
> +     * @throws \JsonException
method definition missing

2023-06-06 07:29 UTC, sriza commented on app/Http/Controllers/Admin/Activity/ActivityController.php
> +
no need for empty line here

2023-06-06 07:33 UTC, sriza commented on app/Http/Controllers/Admin/Activity/ActivityController.php
> +        $element['transactions']['warning_info_text'] = $warning_info_text;
we can assign warning text directly to element->transaction->warning_info_text

2023-06-06 07:36 UTC, sriza commented on app/Http/Controllers/Admin/Activity/RecipientRegionController.php
> +    public function getRecipientRegionManipulatedElementSchema($activity): array
this code can be reused for both recipient region and country. considering adding the test to activity service

2023-06-06 07:38 UTC, sriza commented on app/Http/Controllers/Admin/Activity/TransactionController.php
> +    public function appendInfoTextForRecipientRegionAndCountryInTransaction($activity, &$element, $transactionId): void
place this code in transaction service

2023-06-06 07:38 UTC, sriza commented on app/Http/Controllers/Admin/Activity/TransactionController.php
> +    public function appendInfoTextForSectorInTransaction($activity, &$element, $transactionId): void
place this code in the transaction service

2023-06-06 07:41 UTC, sriza commented on app/IATI/Services/Activity/RecipientRegionService.php
>       * @return bool
place throw before return and add an empty line inbetween

2023-06-06 07:41 UTC, sriza commented on app/IATI/Services/Activity/RecipientRegionService.php
> +     * @throws JsonException
place throw before return

2023-06-06 07:42 UTC, sriza commented on app/IATI/Services/ElementCompleteService.php
> +     * @throws JsonException
place all the throws before return and leave an empty line between them in this file

2023-06-06 07:43 UTC, sriza commented on app/Observers/TransactionObserver.php
> +    private function recipientRegionIsEmptyInTransaction(mixed $recipientRegion): bool
add php docs

2023-06-06 07:43 UTC, sriza commented on app/Observers/TransactionObserver.php
> +    private function recipientCountryIsEmptyInTransaction(mixed $recipientCountry): bool
add php docs

2023-06-06 07:45 UTC, sriza commented on resources/views/vendor/laravel-form-builder/collection.php
> +                                        fill="none"
add svg to different file then use it as such: <svg-vue icon="svg name" class="mr-2"></svg-vue>

2023-06-06 07:45 UTC, sriza commented on resources/views/vendor/laravel-form-builder/collection.php
> +                    if($err !== "")
!empty($err)

2023-06-06 08:01 UTC, Sanilblank requested changes

2023-06-08 11:01 UTC, sriza approved these changes

2023-06-08 11:05 UTC, Sanilblank approved these changes

2023-06-08 11:06 UTC, Sanilblank approved these changes

2023-06-08 11:06 UTC, merged