review: 1213-default-value-extension
younginnovations/iatipublisher pull request #1237
Opened 2023-06-20 07:21 UTC by A4family

2023-06-20 07:38 UTC, Sanilblank requested changes

2023-06-20 07:38 UTC, Sanilblank commented on app/IATI/Repositories/Activity/ActivityRepository.php
>      public function importXmlActivities($activity_id, array $mappedActivity): mixed
change return type

2023-06-20 07:38 UTC, Sanilblank commented on app/IATI/Repositories/Activity/ActivityRepository.php
> +     * @throws BindingResolutionException
can write multiple throw in same line

2023-06-20 07:38 UTC, Sanilblank commented on app/IATI/Repositories/Activity/ActivityRepository.php
> +    public function autoFillSettingsValue($csvValue, $defaultElementName): mixed
change return type

2023-06-22 10:20 UTC, sriza approved these changes

2023-06-22 10:58 UTC, merged