composer and docker updated
younginnovations/iatipublisher pull request #561
Opened 2022-09-29 08:36 UTC by man-git007

2022-09-29 08:44 UTC, bikramtuladhar requested changes

2022-09-29 08:44 UTC, bikramtuladhar commented on Dockerfile
> +    && apk add --no-cache libpq libjpeg-turbo-dev libpng-dev libwebp-dev freetype-dev \
libpq is already installed below
some library are only required for compiling PHP extension and they no longer needed,
check if this case is true for gd
libpq is required even after the extension is installed in system that's why it is added at the end of script

2022-09-29 08:44 UTC, bikramtuladhar commented on Dockerfile
> +    && apk add --no-cache libpq libjpeg-turbo-dev libpng-dev libwebp-dev freetype-dev \
if libjpeg-turbo-dev libpng-dev libwebp-dev freetype-dev are only required to compile then move these depedency at build dependecies

2023-01-19 06:00 UTC, man-git007 commented
Already fixed. Closed manually

2023-01-19 06:00 UTC, closed without merging